# Generated by Django 5.2.3 on 2025-06-14 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=40, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, upload_to='article/%Y/%m', verbose_name='Изображение')),
                ('file', models.FileField(upload_to='uploads/')),
            ],
            options={
                'verbose_name': '#',
                'verbose_name_plural': '#',
            },
        ),
    ]
